permissions:
  contents: write
  pages: write

name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Build and Deploy React app to GitHub Pages
      env:
        MY_EMAIL: toya.rosuello@gmail.com
        MY_NAME: toyadr
      
      run: |
        git config --global user.email $MY_EMAIL
        git config --global user.name $MY_NAME
        git remote set-url origin https://$MY_NAME:${{ secrets.DEPLOY_TOKEN }}@github.com/toyadr/game-dev-portfolio-toya.git
        npm install
        npm run predeploy
        npm run deploy
